
name: build

on:
  push:
    tags: ['v*']
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # manual trigger

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained Eto.Containers.Demo
        dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained Eto.Containers.Demo
        # wrap artifacts in tar archives to maintain permissions intact
        tar --directory=Eto.Containers.Demo/bin/Mac64/Debug/net6.0/osx-x64/publish -cvf Eto.Containers.Demo.Mac.tar Eto.Containers.Demo.app
        tar --directory=Eto.Containers.Demo/bin/Gtk/Debug/net6.0/linux-x64/publish -cvf Eto.Containers.Demo.Gtk.tar Eto.Containers.Demo

    - name: Upload Eto.Containers.Mac artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Eto.Containers.Demo.Mac
        path: Eto.Containers.Demo.Mac.tar

    - name: Upload Eto.Containers.Gtk artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Eto.Containers.Demo.Gtk
        path: Eto.Containers.Demo.Gtk.tar

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet build -c Release Eto.Containers
        dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained Eto.Containers.Demo
    
    - name: Upload Eto.Containers.Wpf artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Eto.Containers.Demo.Wpf
        path: Eto.Containers.Demo/bin/Wpf/Debug/net6.0-windows/win-x64/publish/Eto.Containers.Demo.exe

    - name: Upload nuget artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: ./**/bin/Release/*.nupkg

    - name: Push to nuget.org
      if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      run: dotnet nuget push '.\Eto.Containers\bin\Release\*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
